security:
    firewalls:
        docs:
            pattern: ^/api/v1/docs
            methods: [GET]
            security: false

        api:
            pattern: ^/
            stateless: true
            security: false